apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

resources:
  - ns.yaml
  - generated.yaml
  - pv.yaml
  - pvc.yaml

configMapGenerator:
  - name: prometheus-alert-manager
    files:
      - config/alertmanager.yaml

  - name: prometheus-server
    files:
      - config/alerts
      - config/rules
      - config/prometheus.yaml
